# Auto-label PRs based on files changed
# Contributors can suggest changes to this file via PRs (especially when adding new features/components),
# but maintainers review and approve all label configuration changes.
#
# Format for labeler v5:
# Each label must have an array of config options with 'changed-files' key

# Component labels
id3v1:
  - changed-files:
      - any-glob-to-any-file:
          - audiometa/manager/id3v1/**/*
          - audiometa/utils/id3v1_genre_code_map.py

id3v2:
  - changed-files:
      - any-glob-to-any-file:
          - audiometa/manager/_rating_supporting/_Id3v2Manager.py
          - audiometa/manager/_rating_supporting/**/*id3v2*

vorbis:
  - changed-files:
      - any-glob-to-any-file:
          - audiometa/manager/_rating_supporting/_VorbisManager.py
          - audiometa/manager/_rating_supporting/**/*vorbis*

riff:
  - changed-files:
      - any-glob-to-any-file:
          - audiometa/manager/_rating_supporting/_RiffManager.py
          - audiometa/manager/_rating_supporting/**/*riff*

cli:
  - changed-files:
      - any-glob-to-any-file:
          - audiometa/cli.py
          - audiometa/__main__.py

core:
  - changed-files:
      - any-glob-to-any-file:
          - audiometa/_audio_file.py
          - audiometa/manager/_MetadataManager.py
          - audiometa/utils/UnifiedMetadataKey.py
          - audiometa/utils/MetadataFormat.py

metadata:
  - changed-files:
      - any-glob-to-any-file:
          - audiometa/utils/UnifiedMetadataKey.py

# Type labels
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "**/README.md"
          - "**/CONTRIBUTING.md"
          - "**/CHANGELOG.md"

test:
  - changed-files:
      - any-glob-to-any-file:
          - audiometa/test/**/*
          - "**/test_*.py"
          - "**/conftest.py"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
          - ".github/**/*.yml"
          - ".github/**/*.yaml"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"
          - "setup.py"
          - "setup.cfg"
