name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Call function '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: If applicable, add a minimal code example to reproduce the issue
      placeholder: |
        ```python
        from audiometa import get_unified_metadata

        # Your code here
        ```
      render: python

  - type: dropdown
    id: audio_format
    attributes:
      label: Audio Format
      description: Which audio format(s) are affected?
      options:
        - MP3
        - FLAC
        - WAV
        - Multiple
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: metadata_format
    attributes:
      label: Metadata Format
      description: Which metadata format(s) are affected?
      options:
        - ID3v1
        - ID3v2
        - Vorbis
        - RIFF
        - Multiple
        - Not applicable
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: AudioMeta Version
      description: What version of AudioMeta are you using?
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g., 3.12.0
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message / Traceback
      description: If applicable, paste the full error message or traceback
      placeholder: |
        ```
        Paste error message here
        ```
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Additional context about your environment
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - External tools: [e.g., ffprobe version, flac version]
        - Any other relevant information
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the bug
      placeholder: Add any other context about the problem here...

