name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm always frustrated when...
        This would help me because...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        I would like AudioMeta to...
        This could work by...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        I also considered...
        Another option would be...
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What area does this feature affect?
      options:
        - Core API
        - Metadata Format Support (ID3v1, ID3v2, Vorbis, RIFF)
        - Audio Format Support (MP3, FLAC, WAV)
        - CLI
        - Documentation
        - Error Handling
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe a specific use case or example of how this feature would be used
      placeholder: |
        ```python
        # Example usage
        from audiometa import ...

        # How you would use the new feature
        ```
      render: python

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Check any that apply
      options:
        - label: This feature would require changes to existing API
        - label: This feature would be backward compatible
        - label: This feature would require new dependencies
        - label: This feature would require external tools

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or information about the feature request
      placeholder: Add any other context, screenshots, or examples here...

